#!/usr/bin/env bash
export GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
export AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT=${AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT}
export FIGHTERS_GCS_PATH=${FIGHTERS_GCS_PATH}
export STATS_GCS_PATH=${STATS_GCS_PATH}
export MERGE_GCS_PATH=${MERGE_GCS_PATH}
export UFC_BUCKET=${UFC_BUCKET}
export SERVICE_ACCT_JSON=${SERVICE_ACCT_JSON}